### ISSUE TITLE
Optional directories

### ISSUE THREAD

**Issue by TimeTravelPenguin** [cetz-package/common#2]
Is it possible that [`gallery`](https://github.com/cetz-package/common/blob/26359dfa24a9a24b71d38e9bb856b670e71a9118/scripts/package#L46-L56) can be made optional?

Additionally, can we add a template directory, or add the option for arguments to additional directories/files to include?

I don't have a `gallery` in the project I am working on. However, we have a `previews` (however, I don't know if that will be needed in our `@local`/`@preview`).

I find this repo very helpful in that I don't need to write my own installer, so I thought the request might be worth asking.

Thanks!

**Comment by johannes-wolf** [comment]
Sure, feel free to open a PR. :)

**Comment by TimeTravelPenguin** [comment]
I am looking into this now and I would like to clean this up a little and add an `--include` option to add directories or files. I don't like doing too many bulk bash shenanigans and wondered if you mind if I refactor this to use [bashly](https://github.com/DannyBen/bashly)?

**Comment by johannes-wolf** [comment]
Never used bashly. I think it is a bit too much for such a simple script? There is also an improved/changed version of this script here: https://github.com/typst-community/typst-package-template/tree/main/scripts maybe that one fits better?

**Comment by TimeTravelPenguin** [comment]
Ooohhh, thanks! I somehow missed this and it seems like it might be what I need. Seems to have some extra stuff, too.

Thanks for the link. I am going to close this issue. If there are issues, it will probably be best to open an issue there :)
